version: '3'
services:
 # Nginx server configuration   
  web:
    image: nginx:1.22
    container_name: webserver
    depends_on:
      - docker-mysql
      - php
    links:
      - docker-mysql
      - php
    volumes:
      - D:/DAWDU/docker-php/html:/var/www/html
      - D:/DAWDU/docker-php/nginx:/etc/nginx/conf.d/
    ports:
      - "8080:80"
 # Php-fpm configuration
  php:
    image: php:8.1-fpm
    volumes:
      - D:/DAWDU/docker-php/html:/var/www/html
      - D:/DAWDU/docker-php/php:/usr/local/etc/php/php.ini
 # Mysql configuration
  docker-mysql:
    image: mysql:5.7
    container_name: docker-mysql-demo
    restart: always
    environment:
        - MYSQL_DATABASE=docker_demo
        - MYSQL_ROOT_PASSWORD=root123
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root123
    ports:
        - "3308:3306"
    volumes:
        - /dbdata:/var/lib/mysql